### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory for Fapello

### ISSUE THREAD

**Issue by iansquenet** [Ximaz/megaloader#14] opened 2022-10-06 18:24 UTC
```
C:\Users\Sam\megaloader>python fapello.py
Traceback (most recent call last):
  File "C:\Users\Sam\megaloader\fapello.py", line 12, in <module>
    main()
  File "C:\Users\Sam\megaloader\fapello.py", line 9, in main
    api.download_file(u, output)
  File "C:\Users\Sam\megaloader\plugins\fapello.py", line 49, in download_file
    http_download(url, output, custom_headers={
  File "C:\Users\Sam\megaloader\megaloader\http.py", line 45, in http_download
    with open(output, 'wb+') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'downloads\\ie_0158.jpg'`
```

**Comment by Ximaz** [comment] 2022-10-07 13:10
I actually don't get any error when I try to download this. Can I see the test file you're running ?

**Comment by iansquenet** [comment] 2022-10-07 19:23
> I actually don't get any error when I try to download this. Can I see the test file you're running ?

I'm running the Fapello.py file with just the URL changed.

**Comment by Ximaz** [comment] 2022-10-08 08:53
Yeah I mean, the URL.

**Comment by MiraiTenshiXX** [comment] 2022-11-11 00:07
Hi men, I actually have the same problem.
It shows:
FileNotFoundError: [Errno 2] No such file or directory: 'downloads\\alina-becker_4729.jpg

I only changed the URL.
 Can u solved?

**Comment by MiraiTenshiXX** [comment] 2022-11-11 00:33
Hi men.
You only need to create the folder named "downloads" on the directory of the program.

**Comment by Ximaz** [comment] 2022-11-11 01:15
> Hi men. You only need to create the folder named "downloads" on the directory of the program.

Yeah you right, I forgot to read the end of the error. I didn't event notice. It was not a bug from the code then. You can close this.

**Closed** 2022-11-11 11:20 UTC
